"""Initial schema

Revision ID: 918172c30568
Revises: 
Create Date: 2025-11-29 04:29:35.824403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '918172c30568'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_cycles_status'), 'evaluation_cycles', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('job_family', sa.String(length=100), nullable=True),
    sa.Column('seniority_level', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('behavioral_indicators', sa.Text(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('role_skill_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('required_level', sa.SmallInteger(), nullable=False),
    sa.Column('importance_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('framework_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('importance_weight >= 0 AND importance_weight <= 1', name='ck_importance_weight_range'),
    sa.CheckConstraint('required_level >= 0 AND required_level <= 10', name='ck_required_level_range'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'skill_id', 'framework_version', name='uq_role_skill_framework')
    )
    op.create_index(op.f('ix_role_skill_requirements_role_id'), 'role_skill_requirements', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_skill_requirements_skill_id'), 'role_skill_requirements', ['skill_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_manager_id'), 'users', ['manager_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_cycle_id', sa.UUID(), nullable=False),
    sa.Column('evaluator_id', sa.UUID(), nullable=False),
    sa.Column('evaluator_relationship', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_cycle_id'], ['evaluation_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_evaluation_cycle_id'), 'evaluations', ['evaluation_cycle_id'], unique=False)
    op.create_index(op.f('ix_evaluations_evaluator_id'), 'evaluations', ['evaluator_id'], unique=False)
    op.create_index(op.f('ix_evaluations_user_id'), 'evaluations', ['user_id'], unique=False)
    op.create_table('skills_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_cycle_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('raw_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_cycle_id'], ['evaluation_cycles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_assessments_evaluation_cycle_id'), 'skills_assessments', ['evaluation_cycle_id'], unique=False)
    op.create_index(op.f('ix_skills_assessments_status'), 'skills_assessments', ['status'], unique=False)
    op.create_index(op.f('ix_skills_assessments_user_id'), 'skills_assessments', ['user_id'], unique=False)
    op.create_table('user_skill_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_cycle_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('raw_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_confidence_range'),
    sa.CheckConstraint('score >= 0 AND score <= 10', name='ck_score_range'),
    sa.ForeignKeyConstraint(['evaluation_cycle_id'], ['evaluation_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'evaluation_cycle_id', 'skill_id', 'source', name='uq_user_cycle_skill_source')
    )
    op.create_index(op.f('ix_user_skill_scores_evaluation_cycle_id'), 'user_skill_scores', ['evaluation_cycle_id'], unique=False)
    op.create_index(op.f('ix_user_skill_scores_skill_id'), 'user_skill_scores', ['skill_id'], unique=False)
    op.create_index(op.f('ix_user_skill_scores_user_id'), 'user_skill_scores', ['user_id'], unique=False)
    op.create_table('career_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skills_assessment_id', sa.UUID(), nullable=True),
    sa.Column('path_name', sa.String(length=200), nullable=False),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('feasibility_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('total_duration_months', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('feasibility_score >= 0 AND feasibility_score <= 1', name='ck_feasibility_score_range'),
    sa.ForeignKeyConstraint(['skills_assessment_id'], ['skills_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_paths_skills_assessment_id'), 'career_paths', ['skills_assessment_id'], unique=False)
    op.create_index(op.f('ix_career_paths_status'), 'career_paths', ['status'], unique=False)
    op.create_index(op.f('ix_career_paths_user_id'), 'career_paths', ['user_id'], unique=False)
    op.create_table('evaluation_competency_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 10', name='ck_score_range'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'skill_id', name='uq_evaluation_skill')
    )
    op.create_index(op.f('ix_evaluation_competency_scores_evaluation_id'), 'evaluation_competency_scores', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_evaluation_competency_scores_skill_id'), 'evaluation_competency_scores', ['skill_id'], unique=False)
    op.create_table('skills_assessment_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skills_assessment_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('current_level', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_level', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gap_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('readiness_percentage', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_level >= 0 AND current_level <= 10', name='ck_current_level_range'),
    sa.CheckConstraint('gap_score >= 0 AND gap_score <= 10', name='ck_gap_score_range'),
    sa.CheckConstraint('readiness_percentage >= 0 AND readiness_percentage <= 1', name='ck_readiness_percentage_range'),
    sa.CheckConstraint('score >= 0 AND score <= 10', name='ck_score_range'),
    sa.CheckConstraint('target_level >= 0 AND target_level <= 10', name='ck_target_level_range'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skills_assessment_id'], ['skills_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_assessment_items_item_type'), 'skills_assessment_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_skills_assessment_items_role_id'), 'skills_assessment_items', ['role_id'], unique=False)
    op.create_index(op.f('ix_skills_assessment_items_skill_id'), 'skills_assessment_items', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skills_assessment_items_skills_assessment_id'), 'skills_assessment_items', ['skills_assessment_id'], unique=False)
    op.create_table('ai_calls_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('evaluation_cycle_id', sa.UUID(), nullable=True),
    sa.Column('skills_assessment_id', sa.UUID(), nullable=True),
    sa.Column('career_path_id', sa.UUID(), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_path_id'], ['career_paths.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_cycle_id'], ['evaluation_cycles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skills_assessment_id'], ['skills_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_calls_log_career_path_id'), 'ai_calls_log', ['career_path_id'], unique=False)
    op.create_index(op.f('ix_ai_calls_log_evaluation_cycle_id'), 'ai_calls_log', ['evaluation_cycle_id'], unique=False)
    op.create_index(op.f('ix_ai_calls_log_service_name'), 'ai_calls_log', ['service_name'], unique=False)
    op.create_index(op.f('ix_ai_calls_log_skills_assessment_id'), 'ai_calls_log', ['skills_assessment_id'], unique=False)
    op.create_index(op.f('ix_ai_calls_log_user_id'), 'ai_calls_log', ['user_id'], unique=False)
    op.create_table('career_path_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_path_id', sa.UUID(), nullable=False),
    sa.Column('target_role_id', sa.UUID(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_path_id'], ['career_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_path_id', 'step_number', name='uq_career_path_step_number')
    )
    op.create_index(op.f('ix_career_path_steps_career_path_id'), 'career_path_steps', ['career_path_id'], unique=False)
    op.create_table('development_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_path_step_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('estimated_effort_hours', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_path_step_id'], ['career_path_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_development_actions_career_path_step_id'), 'development_actions', ['career_path_step_id'], unique=False)
    op.create_index(op.f('ix_development_actions_skill_id'), 'development_actions', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_development_actions_skill_id'), table_name='development_actions')
    op.drop_index(op.f('ix_development_actions_career_path_step_id'), table_name='development_actions')
    op.drop_table('development_actions')
    op.drop_index(op.f('ix_career_path_steps_career_path_id'), table_name='career_path_steps')
    op.drop_table('career_path_steps')
    op.drop_index(op.f('ix_ai_calls_log_user_id'), table_name='ai_calls_log')
    op.drop_index(op.f('ix_ai_calls_log_skills_assessment_id'), table_name='ai_calls_log')
    op.drop_index(op.f('ix_ai_calls_log_service_name'), table_name='ai_calls_log')
    op.drop_index(op.f('ix_ai_calls_log_evaluation_cycle_id'), table_name='ai_calls_log')
    op.drop_index(op.f('ix_ai_calls_log_career_path_id'), table_name='ai_calls_log')
    op.drop_table('ai_calls_log')
    op.drop_index(op.f('ix_skills_assessment_items_skills_assessment_id'), table_name='skills_assessment_items')
    op.drop_index(op.f('ix_skills_assessment_items_skill_id'), table_name='skills_assessment_items')
    op.drop_index(op.f('ix_skills_assessment_items_role_id'), table_name='skills_assessment_items')
    op.drop_index(op.f('ix_skills_assessment_items_item_type'), table_name='skills_assessment_items')
    op.drop_table('skills_assessment_items')
    op.drop_index(op.f('ix_evaluation_competency_scores_skill_id'), table_name='evaluation_competency_scores')
    op.drop_index(op.f('ix_evaluation_competency_scores_evaluation_id'), table_name='evaluation_competency_scores')
    op.drop_table('evaluation_competency_scores')
    op.drop_index(op.f('ix_career_paths_user_id'), table_name='career_paths')
    op.drop_index(op.f('ix_career_paths_status'), table_name='career_paths')
    op.drop_index(op.f('ix_career_paths_skills_assessment_id'), table_name='career_paths')
    op.drop_table('career_paths')
    op.drop_index(op.f('ix_user_skill_scores_user_id'), table_name='user_skill_scores')
    op.drop_index(op.f('ix_user_skill_scores_skill_id'), table_name='user_skill_scores')
    op.drop_index(op.f('ix_user_skill_scores_evaluation_cycle_id'), table_name='user_skill_scores')
    op.drop_table('user_skill_scores')
    op.drop_index(op.f('ix_skills_assessments_user_id'), table_name='skills_assessments')
    op.drop_index(op.f('ix_skills_assessments_status'), table_name='skills_assessments')
    op.drop_index(op.f('ix_skills_assessments_evaluation_cycle_id'), table_name='skills_assessments')
    op.drop_table('skills_assessments')
    op.drop_index(op.f('ix_evaluations_user_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_evaluator_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_evaluation_cycle_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_manager_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_skill_requirements_skill_id'), table_name='role_skill_requirements')
    op.drop_index(op.f('ix_role_skill_requirements_role_id'), table_name='role_skill_requirements')
    op.drop_table('role_skill_requirements')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_evaluation_cycles_status'), table_name='evaluation_cycles')
    op.drop_table('evaluation_cycles')
    # ### end Alembic commands ###
